/* eslint-disable quotes */
const en = {
  Add_an_option: 'Add an option',
  Find_an_option: 'Find a option',
  No_options_available: 'No options available',
  Current_option: 'Current option',
  No_option: 'No option',
  Choose_an_option: 'Choose an option',
  Add_a_collaborator: 'Add a collaborator',
  Search_collaborator: 'Search collaborator',
  No_collaborators_available: 'No collaborators available',
  Done: 'Done',
  Choose_a_collaborator: 'Choose a collaborator',
  Please_input: 'Please input',
  Please_select: 'Please select',
  Clear: 'Clear',
  Are_you_sure_you_want_to_delete_this_file: 'Are you sure you want to delete this file?',
  Are_you_sure_you_want_to_delete_this_image: 'Are you sure you want to delete this image?',
  Cancel: 'Cancel',
  Delete: 'Delete',
  Find_a_department: 'Find a department',
  No_departments_available: 'No departments available',
  Current_user_department: 'Current user\'s department',
  Current_user_department_and_sub: 'Current user\'s department and sub-departments',
  Specific_departments: 'Specific departments',
  Deleted_department: 'Deleted department',
  Add_filter: 'Add filter',
  Submit: 'Submit',
  No_filters: 'No filters',
  Select_an_option: 'Select an option',
  Add_collaborator: 'Add collaborator',
  Add_a_creator: 'Add a creator',
  Add_a_last_modifier: 'Add a last modifier',
  Invalid_filter: 'Invalid filter',
  Find_column: 'Find column',
  No_results: 'No results',
  'Select_option(s)': 'Select option(s)',
  "contains": "contains",
  "does_not_contain": "does not contain",
  "is": "is",
  "is_not": "is not",
  "equal": "\u003d",
  "not_equal": "\u2260",
  "less": "\u003C",
  "greater": "\u003E",
  "less_or_equal": "\u2264",
  "greater_or_equal": "\u2265",
  "is_empty": "is empty",
  "is_not_empty": "is not empty",
  "is_within": "is within",
  "is_before": "is before",
  "is_after": "is after",
  "is_on_or_before": "is on or before",
  "is_on_or_after": "is on or after",
  "has_any_of": "has any of",
  "has_all_of": "has all of",
  "has_none_of": "has none of",
  "is_exactly": "is exactly",
  "is_current_user_ID": "is current user's ID",
  "Current_date": "Current date",
  "Specific_date": "Specific date",
  "x_days_before_current_date": "x days before current date",
  "x_days_after_current_date": "x days after current date",
  "is_any_of": "is any of",
  "is_none_of": "is none of",
  "include_me": "include the current user",
  "today": "today",
  "tomorrow": "tomorrow",
  "yesterday": "yesterday",
  "one_week_ago": "one week ago",
  "one_week_from_now": "one week from now",
  "one_month_ago": "one month ago",
  "one_month_from_now": "one month from now",
  "number_of_days_ago": "number of days ago",
  "number_of_days_from_now": "number of days from now",
  "exact_date": "exact date",
  "the_past_week": "last week",
  "the_past_month": "last month",
  "the_past_year": "last year",
  "the_next_week": "the next week",
  "the_next_month": "the next month",
  "the_next_year": "the next year",
  "the_next_numbers_of_days": "the next numbers of days",
  "the_past_numbers_of_days": "the past numbers of days",
  "this_week": "this week",
  "this_month": "this month",
  "this_year": "this year",

};

export default en;
