const en = {
  Add_an_option: 'Add an option',
  Find_an_option: 'Find a option',
  No_options_available: 'No options available',
  Current_option: 'Current option',
  No_option: 'No option',
  Choose_an_option: 'Choose an option',
  Add_a_collaborator: 'Add a collaborator',
  Find_a_collaborator: 'Find a collaborator',
  No_collaborators_available: 'No collaborators available',
  Done: 'Done',
  Choose_a_collaborator: 'Choose a collaborator',
  Please_input: 'Please input',
  Please_select: 'Please select',
  Clear: 'Clear',
  Are_you_sure_you_want_to_delete_this_file: 'Are you sure you want to delete this file?',
  Are_you_sure_you_want_to_delete_this_image: 'Are you sure you want to delete this image?',
  Cancel: 'Cancel',
  Delete: 'Delete',
  Add_filter: 'Add filter',
  Submit: 'Submit',
  No_filters_applied_to_this_view: 'No_filters_applied_to_this_view',
  No_filters: 'No_filters',
  Find_a_collaborator: 'Find_a_collaborator',
  Today: 'Today',
  Tomorrow: 'Tomorrow',
  Yesterday: 'Yesterday',
  One_week_ago: 'One week ago',
  One_week_from_now: 'One week from now',
  One_month_ago: 'One month ago',
  One_month_from_now: 'One month from now',
  Number_of_days_ago: 'Number of days ago',
  Number_of_days_from_now: 'Number of days from now',
  Exact_date: 'Exact date',
  Last_week: 'Last week',
  Last_month: 'Last month',
  Last_year: 'Last year',
  The_next_week: 'The next week',
  The_next_month: 'The next month',
  The_next_year: 'The next year',
  The_next_numbers_of_days: 'The next numbers of days',
  The_past_numbers_of_days: 'The past numbers of days',
  This_week: 'This week',
  This_month: 'This month',
  This_year: 'This year',

  Select_an_option: 'Select_an_option',
  Find_an_option: 'Find_an_option',
  No_options_available: 'No_options_available',
  Add_collaborator: 'Add_collaborator',
  Add_a_creator: 'Add_a_creator',
  Add_a_last_modifier: 'Add_a_last_modifier',
  Invalid_filter: 'Invalid_filter',
  Find_column: 'Find_column',
  No_results: 'No_results',
};

export default en;
