/* eslint-disable quotes */
const es = {
  "Add_an_option": "Add an option",
  "Search_option": "Search option",
  "No_options_available": " No hay opciones disponibles",
  "Current_option": "Opción actual",
  "No_option": "Sin opciones",
  "Choose_an_option": "Choose an option",
  "Add_a_collaborator": "Añadir a colaborador",
  "Search_collaborator": "Encuentra un colaborador",
  "No_collaborators_available": "No hay colaboradores disponibles.",
  "Done": "Hecho",
  "Choose_a_collaborator": "Choose a collaborator",
  "Please_input": "Please input",
  "Please_select": "Please select",
  "Clear": "Limpiar",
  "Are_you_sure_you_want_to_delete_this_image": "¿Seguro que deseas borrar esta imagen?",
  "Are_you_sure_you_want_to_delete_this_file": "¿Está seguro de querer eliminar este archivo?",
  "Cancel": "Cancelar",
  "Delete": "Borrar",
  "Search_department": "Search department",
  "No_departments_available": "No departments available",
  "Current_user_department": "Current user's department",
  "Current_user_department_and_sub": "Current user's department and sub-departments",
  "Specific_departments": "Specific departments",
  "Deleted_department": "Deleted department",
  "Add_filter": "Añadir filtro",
  "Submit": "Enviar",
  "No_filters": "Sin filtros",
  "Select_an_option": "Elige una opción",
  "Add_collaborator": "Añadir colaborador",
  "Add_a_creator": "Añadir un creador",
  "Add_a_last_modifier": "Añadir un último en modificar",
  "Invalid_filter": "Filtro inválido",
  "Search_column": "Search column",
  "No_results": "Sin resultados.",
  "Select_option(s)": "Elegir opción(es)",
  "contains": "contiene",
  "does_not_contain": "no contiene",
  "is": "es",
  "is_not": "no es",
  "equal": "=",
  "not_equal": "≠",
  "less": "<",
  "greater": ">",
  "less_or_equal": "≤",
  "greater_or_equal": "≥",
  "is_empty": "está en blanco",
  "is_not_empty": "no está en blanco",
  "is_within": "es entre",
  "is_before": "es previo a",
  "is_after": "es posterior a",
  "is_on_or_before": "es en o antes de",
  "is_on_or_after": "es en o después de",
  "has_any_of": "tiene al menos uno de",
  "has_all_of": "tiene todos de",
  "has_none_of": "no tiene ninguno de",
  "is_exactly": "es exactamente",
  "is_current_user_ID": "es el ID del usuario actual",
  "Current_date": "Fecha actual",
  "Specific_date": "Fecha específica",
  "x_days_before_current_date": "x días antes de hoy",
  "x_days_after_current_date": "x días después de hoy",
  "is_any_of": "es al menos uno de",
  "is_none_of": "no es ninguno de",
  "include_me": "incluir el usuario actual",
  "today": "hoy",
  "tomorrow": "mañana",
  "yesterday": "ayer",
  "one_week_ago": "hace una semana",
  "one_week_from_now": "una semana desde ahora",
  "one_month_ago": "hace un mes",
  "one_month_from_now": "un mes desde ahora",
  "number_of_days_ago": "hace tantos días",
  "number_of_days_from_now": "tantos días desde ahora",
  "exact_date": "fecha exacta",
  "the_past_week": "la semana pasada",
  "the_past_month": "el mes pasado",
  "the_past_year": "el año pasado",
  "the_next_week": "la próxima semana",
  "the_next_month": "el próximo mes",
  "the_next_year": "el próximo año",
  "the_next_numbers_of_days": "pasados estos días",
  "the_past_numbers_of_days": "en los últimos días",
  "this_week": "esta semana",
  "this_month": "este mes",
  "this_year": "este año",
  "last_week": "la semana pasada",
  "last_month": "el mes pasado",
  "last_year": "el año pasado",
  "URL_is_invalid": "URL no válida",
  "Select_department": "Select department",
  "Default": "Incumplimiento de contrato",
  "Custom": "Costumbres",
  "Recently_used": "Recientemente usado",
};

export default es;
