/* eslint-disable quotes */
const fr = {
  "Add_an_option": "Ajouter une option",
  "Search_option": "Trouver une option",
  "No_options_available": "Il n'y a pas d'options disponibles.",
  "Current_option": "Option actuelle",
  "No_option": "Aucune option",
  "Choose_an_option": "Choisis une option",
  "Add_a_collaborator": "Ajouter un collaborateur",
  "Search_collaborator": "Trouver un collaborateur",
  "No_collaborators_available": "Aucun collaborateur n'est disponible.",
  "Done": "Fait",
  "Choose_a_collaborator": "Choisissez un collaborateur",
  "Please_input": "Veuillez saisir",
  "Please_select": "Veuillez sélectionner",
  "Clear": "Effacer",
  "Are_you_sure_you_want_to_delete_this_image": "Êtes-vous sûr de vouloir supprimer cette image?",
  "Are_you_sure_you_want_to_delete_this_file": "Êtes-vous sûr de vouloir supprimer ce fichier?",
  "Cancel": "Annuler",
  "Delete": "Supprimer",
  "Search_department": "Chercher un département",
  "No_departments_available": "Aucun département n'est disponible.",
  "Current_user_department": "Département de l'utilisateur actuel",
  "Current_user_department_and_sub": "Département et sous-départements de l'utilisateur actuel",
  "Specific_departments": "Départements spécifiques",
  "Deleted_department": "Le département a été supprimé.",
  "Add_filter": "Ajouter un filtre",
  "No_filters": "Aucun filtre",
  "Submit": "Soumettre",
  "Select_an_option": "Sélectionner une option",
  "Add_collaborator": "Ajouter un collaborateur",
  "Add_a_creator": "Ajouter un créateur",
  "Add_a_last_modifier": "Ajouter un dernier éditeur",
  "Invalid_filter": "Filtre invalide",
  "Search_column": "Rechercher une colonne",
  "No_results": "Aucun résultat",
  "Select_option(s)": "Selectionner une ou plusieurs options",
  "contains": "contient",
  "does_not_contain": "ne contient pas",
  "is": "est égale à",
  "is_not": "est différente de",
  "equal": "=",
  "not_equal": "≠",
  "less": "<",
  "greater": ">",
  "less_or_equal": "≤",
  "greater_or_equal": "≥",
  "is_empty": "est vide",
  "is_not_empty": "n'est pas vide",
  "is_within": "est pendant",
  "is_before": "est avant",
  "is_after": "est après",
  "is_on_or_before": "est le ou avant",
  "is_on_or_after": "est le ou après",
  "has_any_of": "contient au moins un",
  "has_all_of": "contient tout",
  "has_none_of": "ne contient aucun",
  "is_exactly": "est exactement",
  "is_current_user_ID": "est l'ID de l'utilisateur connecté",
  "Current_date": "Date actuelle",
  "Specific_date": "Date spécifique",
  "x_days_before_current_date": "Jour avant la date actuelle",
  "x_days_after_current_date": "Jour après la data actuelle",
  "is_any_of": "contient au moins un",
  "is_none_of": "ne contient aucun",
  "include_me": " Inclure l'utilisateur actuel",
  "today": "aujourd'hui",
  "tomorrow": "demain",
  "yesterday": "hier",
  "one_week_ago": "il y a une semaine",
  "one_week_from_now": "dans une semaine",
  "one_month_ago": "il y a un mois",
  "one_month_from_now": "dans un mois",
  "number_of_days_ago": "il y a tels jours",
  "number_of_days_from_now": "dans tels jours",
  "exact_date": "date exacte",
  "the_past_week": "la semaine dernière",
  "the_past_month": "le mois dernier",
  "the_past_year": "l'année dernière",
  "the_next_week": "la semaine prochaine",
  "the_next_month": "le mois prochain",
  "the_next_year": "l'année prochaine",
  "the_next_numbers_of_days": "au cours de tels prochains jours",
  "the_past_numbers_of_days": "au cours de tels derniers jours",
  "this_week": "cette semaine",
  "this_month": "ce mois",
  "this_year": "cette année",
  "last_week": "la semaine dernière",
  "last_month": "le mois dernier",
  "last_year": "l'année dernière",
};

export default fr;
