/* eslint-disable quotes */
const pt = {
  "Add_an_option": "Adicione uma opção",
  "Find_an_option": "Encontre uma opção",
  "No_options_available": "Sem opções disponíveis",
  "Current_option": "Opção atual",
  "No_option": "Nenhuma opção",
  "Choose_an_option": "Escolha uma opção",
  "Add_a_collaborator": "Adicionar um colaborador",
  "Search_collaborator": "Encontre um colaborador",
  "No_collaborators_available": "Nenhum colaborador disponível.",
  "Done": "Feita",
  "Choose_a_collaborator": "Choose a collaborator",
  "Please_input": "Please input",
  "Please_select": "Please select",
  "Clear": "Clara",
  "Are_you_sure_you_want_to_delete_this_image": "Tem certeza de que deseja apagar esta imagem?",
  "Are_you_sure_you_want_to_delete_this_file": "Tem certeza de que deseja excluir este arquivo?",
  "Cancel": "Cancelar",
  "Delete": "Excluir",
  "Find_a_department": "Find a department",
  "No_departments_available": "No departments available",
  "Current_user_department": "Current user's department",
  "Current_user_department_and_sub": "Current user's department and sub-departments",
  "Specific_departments": "Specific departments",
  "Deleted_department": "Deleted department",
  "Add_filter": "Adicione o filtro",
  "Submit": "Enviar",
  "No_filters": "Sem filtros",
  "Select_an_option": "Selecione uma opção",
  "Add_collaborator": "Adicione o colaborador",
  "Add_a_creator": "Adicione um Criador",
  "Add_a_last_modifier": "Adicione um último modificador",
  "Invalid_filter": "Filtro inválido",
  "Find_column": "Encontrar coluna",
  "No_results": "Sem resultados.",
  "Select_option(s)": "Selecione as opções)",
  "contains": "contém",
  "does_not_contain": "não contém",
  "is": "é",
  "is_not": "não é",
  "equal": "=",
  "not_equal": "≠",
  "less": "<",
  "greater": ">",
  "less_or_equal": "≤",
  "greater_or_equal": "≥",
  "is_empty": "está vazia",
  "is_not_empty": "não está vazio",
  "is_within": "está dentro",
  "is_before": "é antes",
  "is_after": "é depois",
  "is_on_or_before": "está ligado ou antes",
  "is_on_or_after": "está ligado ou depois",
  "has_any_of": "tem qualquer um",
  "has_all_of": "tem tudo de",
  "has_none_of": "não tem nenhum",
  "is_exactly": "é exatamente",
  "is_current_user_ID": "é o ID do usuário atual",
  "Current_date": "Data atua",
  "Specific_date": "Específico",
  "x_days_before_current_date": "x dias antes da data atual",
  "x_days_after_current_date": "x dias após a data atual",
  "is_any_of": "é qualquer um",
  "is_none_of": "não é nenhum",
  "include_me": "incluir o usuário atual",
  "today": "hoje",
  "tomorrow": "amanhã",
  "yesterday": "ontem",
  "one_week_ago": "uma semana atrás",
  "one_week_from_now": "daqui a uma semana",
  "one_month_ago": "um mês atrás",
  "one_month_from_now": "um mês atrás",
  "number_of_days_ago": "número de dias atrás",
  "number_of_days_from_now": "número de dias a partir de agora",
  "exact_date": "data exata",
  "the_past_week": "semana anterior",
  "the_past_month": "mês passado",
  "the_past_year": "ano passado",
  "the_next_week": "a próxima semana",
  "the_next_month": "o próximo mês",
  "the_next_year": "no próximo ano",
  "the_next_numbers_of_days": "os próximos números de dias",
  "the_past_numbers_of_days": "os últimos números de dias",
  "this_week": "essa semana",
  "this_month": "este mês",
  "this_year": "este ano",
  "Select_department": "Select department",
};

export default pt;
