/* eslint-disable quotes */
const ru = {
  "Add_an_option": "Add an option",
  "Search_option": "Search option",
  "No_options_available": "Нет доступных вариантов.",
  "Current_option": "Текущая опция",
  "No_option": "Нет опций",
  "Choose_an_option": "Choose an option",
  "Add_a_collaborator": "Add a collaborator",
  "Search_collaborator": "Найти сотрудников",
  "No_collaborators_available": "Нет сотрудников.",
  "Done": "Выполнено",
  "Choose_a_collaborator": "Choose a collaborator",
  "Please_input": "Please input",
  "Please_select": "Please select",
  "Clear": "Очистить",
  "Are_you_sure_you_want_to_delete_this_image": "Are you sure you want to delete this image?",
  "Are_you_sure_you_want_to_delete_this_file": "Are you sure you want to delete this file?",
  "Cancel": "Отменить",
  "Delete": "Удалить",
  "Search_department": "Search department",
  "No_departments_available": "No departments available",
  "Current_user_department": "Current user's department",
  "Current_user_department_and_sub": "Current user's department and sub-departments",
  "Specific_departments": "Specific departments",
  "Deleted_department": "Deleted department",
  "Add_filter": "Добавить фильтр",
  "Submit": "Сохранить",
  "No_filters": "No filters",
  "Select_an_option": "Выберите опцию",
  "Add_collaborator": "Add collaborator",
  "Add_a_creator": "Добавить создателя",
  "Add_a_last_modifier": "Добавить последний изменивший",
  "Invalid_filter": "Invalid filter",
  "Search_column": "Search column",
  "No_results": "Нет результатов.",
  "Select_option(s)": "Выберите опцию(и)",
  "contains": "содержит",
  "does_not_contain": "не содержит",
  "is": "является",
  "is_not": "не является",
  "equal": "=",
  "not_equal": "≠",
  "less": "<",
  "greater": ">",
  "less_or_equal": "≤",
  "greater_or_equal": "≥",
  "is_empty": "пусто",
  "is_not_empty": "не пусто",
  "include_me": "включить текущего пользователя",
  "is_within": "внутри...",
  "is_before": "раньше ...",
  "is_after": "после ...",
  "is_on_or_before": "сейчас или раньше ...",
  "is_on_or_after": "сейчас или после ...",
  "has_any_of": "имеет какой-либо из ...",
  "has_all_of": "есть все ...",
  "has_none_of": "не имеет ни одного из них...",
  "is_exactly": "точно ...",
  "is_current_user_ID": "это идентификатор текущего пользователя",
  "Current_date": "Current date",
  "Specific_date": "Specific date",
  "x_days_before_current_date": "X days before current date",
  "x_days_after_current_date": "X days after current date",
  "is_any_of": "любой из ...",
  "is_none_of": "кроме ...",
  "today": "Сегодня",
  "tomorrow": "завтра",
  "yesterday": "вчера",
  "one_week_ago": "неделю назад",
  "one_week_from_now": "через неделю",
  "one_month_ago": "месяц назад",
  "one_month_from_now": "через месяц",
  "number_of_days_ago": "количество дней назад",
  "number_of_days_from_now": "количество дней с этого момента",
  "exact_date": "точная дата",
  "the_past_week": "прошлая неделя",
  "the_past_month": "прошлый месяц",
  "the_past_year": "прошлый год",
  "the_next_week": "на следующей неделе",
  "the_next_month": "в следующем месяце",
  "the_next_year": "в следующем году",
  "the_next_numbers_of_days": "через дней...",
  "the_past_numbers_of_days": "до дней ...",
  "this_week": "на этой неделе",
  "this_month": "в этом месяце",
  "this_year": "в этом году",
  "last_week": "last week",
  "last_month": "last month",
  "last_year": "last year",
  "URL_is_invalid": "URL-адрес недействителен",
};

export default ru;
