const zh_CN = {
  Add_an_option: '添加一个选项',
  Find_an_option: '查找标签',
  No_options_available: '没有找到标签。',
  Current_option: '当前标签',
  No_option: '没有标签',
  Choose_an_option: '选择一个标签',
  Add_a_collaborator: '添加协作者',
  Find_a_collaborator: '查找协作者',
  No_collaborators_available: '没有找到协作者',
  Done: '完成',
  Choose_a_collaborator: '选择一个协作者',
  Please_input: '请输入',
  Please_select: '请选择',
  Clear: '清空',
  Are_you_sure_you_want_to_delete_this_file: '你确定要删除此文件吗？',
  Are_you_sure_you_want_to_delete_this_image: '你确定要删除此图片吗？',
  Cancel: '取消',
  Delete: '删除',
  Find_a_department: "查找部门",
  Current_user_department: "当前用户的部门",
  Current_user_department_and_sub: "当前用户的部门和子部门",
  Specific_departments: "具体部门",
  Deleted_department: "已经删除的部门",
};

export default zh_CN;
